# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_BGwYfDRIQM5fu_83Tq7Mn32s6yApuek
"""

def policy_iteration(env, policy_evaluation_fn=policy_evaluation, discount_factor=1.0):

    def one_step_lookahead(state, V):
        action_values = np.zeros(env.action_space.n)

        for action in range(env.action_space.n):
            for probability, next_state, reward, done in env.P[state][action]:
                action_values[action] += probability * (
                    reward + discount_factor * V[next_state]
                )

        return action_values

    policy = np.ones(
        [env.observation_space.n, env.action_space.n]
    ) / env.action_space.n

    while True:

        V = policy_evaluation_fn(env,policy,discount_factor)

        policy_stable = True
        new_policy = np.zeros_like(policy)

        for state in range(env.observation_space.n):

            action_values = one_step_lookahead(state, V)  # Store the expected value of each action

            best_action = np.argmax(action_values)

            new_policy[state, best_action] = 1.0

            old_action = np.argmax(policy[state])
            # If the best action differs from the previous action,
            # the policy has not yet converged
            if old_action != best_action:
                policy_stable = False

        policy = new_policy

        if policy_stable:
            return policy, V